### ISSUE TITLE
Patching exiobase

### ISSUE THREAD

**Issue by RosalieHagenaars** [MaximeAgez/pylcaio#5]
Could you provide some info on what the xlsx file patching_exiobase represents? I see it is used for constructing the gamma matrix (where the STAM_table is elemently multiplied with the patching table), however, if I do this in Excel I get a different result from the gamma filter shown in supplementary table of the paper Agez et al. (2020).

**Comment by MaximeAgez** [comment]
Hi Rosalie. If I remember correctly (I didn't document enough what I did at the time apparently) this "Patching_exiobase" file is an additional layer to the STAM matrix, i.e., the one you see in the SI of the article and in the STAM_table.xlsx file within the Data folder.

Its role is to forcefully set to zero other EEIO complements. These additional elements are mostly related to the operation of a canteen basically. Why are are doing that? Because we considered that inputs of food for the operation of a canteen should not be linked to the production of a product. The argument is that your employees could eat outside of your canteen (bring your meal or go to the local Subway or whatnot) and then the footprint of eating is not attributed to your product anymore, but to the employee.

If you disagree with the approach you can put 1s in that matrix instead.
