### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'todense'

### ISSUE THREAD

**Issue by XDannn** [MaximeAgez/pylcaio#7]
Hi, Maxime Agez,
Thanks for sharing your excellent work about the Hybrid LCA database generated using Ecoinvent and EXIOBASE.
I want to construct the hybrid LCA ecoinvent 3.8_exiobase 3.8.1. 
Due to specific additional features are not available for hybridization ecoinvent 3.8 with exiobase, i made the following settings. 
path_to_capitals = ''
complete_extensions = False
impact_world = False
regionalized = False
lcaio_object = database_loader.combine_ecoinvent_exiobase(path_to_capitals=path_to_capitals, complete_extensions=complete_extensions, impact_world=impact_world, regionalized=regionalized)
However, when i tried to update hybrid-ecoinvent, I got the following error. “AttributeError: 'DataFrame' object has no attribute 'todense'.” Could you please tell me how can I deal with this problem? Thank you very much.

**Comment by XDannn** [comment]
![1](https://user-images.githubusercontent.com/107393718/220810269-f7855bec-2280-491d-8de8-d2ea01c6e7de.jpg)

**Comment by MaximeAgez** [comment]
Hi @XDannn,
I believe you must have then called `lcaio_object.hybridize('STAM', True)` while it should be `lcaio_object.hybridize('STAM', False)` since the second argument states if you are endogenizing capitals or not. That's not really clear from the Jupyter notebook. I should change that. Tell me if my guess is correct or not :)

**Comment by XDannn** [comment]
Hi, Maxime Agez,
According to your instructions, my problem has been solved.
Thanks very much!
Best regards.
